---- https://github.com/goolord/alpha-nvim
--local alpha = require('alpha')
--local dashboard = require('alpha.themes.dashboard')
--
--dashboard.section.header.val = {
--  '',
--  '𝗦  𝗢  𝗟  𝗔  𝗥  𝗜  𝗭  𝗘  𝗗',
--  '',
--}
--
--dashboard.section.buttons.val = {
--  dashboard.button('n', ':enew       ▏ New file', ':enew<CR>'),
--  dashboard.button('.', ':e .        ▏ Browse', ':e .<CR>'),
--  dashboard.button('s', '<Space>fs   ▏ File select', ":lua require('modille.fuzzy_finder').project_files()<CR>"),
--  dashboard.button(
--    'g',
--    '<Space>fg   ▏ File grep',
--    ":lua require('telescope.builtin').grep_string({ search = vim.fn.input('🔍 ')})<CR>"
--  ),
--  dashboard.button('o', '<Space>fos  ▏ File old select', ':Telescope oldfiles<CR>'),
--}
--
--alpha.setup(dashboard.opts)
--
--vim.cmd([[
--    autocmd FileType alpha setlocal nofoldenable
--]])
