# Custom MOTD
MOTD_SCRIPT="$HOME/git/github.com/modille/motd/motd.sh"
[[ -s $MOTD_SCRIPT ]] && source $MOTD_SCRIPT

# Uncomment and run zprof at the end to profile startup time
# zmodload zsh/zprof

# rbenv
# Don't forget to `rbenv rehash` after installing new executables
eval "$(rbenv init - --no-rehash zsh)"

# direnv
if hash direnv 2>/dev/null; then
  eval "$(direnv hook zsh)"
fi

# iTerm2 shell integration
# ITERM_SHELL_INTEGRATION="$HOME/.iterm2_shell_integration.zsh"
# [[ -s $ITERM_SHELL_INTEGRATION ]] && source $ITERM_SHELL_INTEGRATION

# NVM
# Adapted from https://github.com/allanjamesvestal/fast-zsh-nvm
# Gives you a prompt sooner, but you may notice a slight delay if typing right away
export NVM_DIR="$HOME/.nvm"
function load_nvm() {
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" --no-use
  # [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"

  autoload -U add-zsh-hook
  load-nvmrc() {
    if [[ -f .nvmrc && -r .nvmrc ]]; then
      nvm use >/dev/null 2>&1
    elif [[ $(nvm version) != $(nvm version default) ]]; then
      echo "Reverting to nvm default version"
      nvm use default
    fi
  }
  add-zsh-hook chpwd load-nvmrc
  load-nvmrc
}
async_start_worker nvm_worker -n
async_register_callback nvm_worker load_nvm
async_job nvm_worker sleep 0.1

# Uncomment and load zprof at the top to profile startup time
# zprof
