# .zshenv

export EDITOR='nvim'
export JRUBY_OPTS='--dev'
export KEYTIMEOUT=25 # Reduce delay when hitting ESC, but not too low to interfere with surround module bindings
export VISUAL='nvim'

# Additions to PATH

# Custom
export PATH="$HOME/local/bin:$PATH"
# Go
export GOPATH="$HOME/go"
[[ -d $GOPATH ]] && export PATH="$PATH:$GOPATH/bin"
# Krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
# Node
export NODEPATH="/usr/local/opt/node@8"
[[ -d $NODEPATH ]] && export PATH="$PATH:$NODEPATH/bin"
# Python
export LIB_PYTHON_PATH="$HOME/Library/Python/3.7"
[[ -d $LIB_PYTHON_PATH ]] && export PATH="$PATH:$LIB_PYTHON_PATH/bin"
# rbenv
export RBENVPATH="$HOME/.rbenv"
[[ -d $RBENVPATH ]] && export PATH="$PATH:$RBENVPATH/bin"
[[ -d $RBENVPATH ]] && export PATH="$PATH:$RBENVPATH/shims"
export RBENV_SHELL=zsh
# Rust
export CARGOPATH="$HOME/.cargo"
[[ -d $CARGOPATH ]] && export PATH="$PATH:$CARGOPATH/bin"

# Homebrew
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"

# https://github.com/brianmario/mysql2/issues/795
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/opt/openssl/lib"

# Pipe less to highlight
export LESSOPEN="| /usr/local/bin/highlight %s --out-format xterm256 --quiet --force --style solarized-light "
export LESS=" -R"

# Quiet direnv
export DIRENV_LOG_FORMAT=

# ruby-build
# To link Rubies to Homebrew's OpenSSL 1.1 (which is upgraded) add the following to your ~/.zshrc:
# Note: this may interfere with building old versions of Ruby (e.g <2.4) that use OpenSSL <1.1.
# export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=/usr/local/opt/openssl@1.1"
