# .zshenv

export EDITOR='nvim'
export JRUBY_OPTS='--dev'
export KEYTIMEOUT=25 # Reduce delay when hitting ESC, but not too low to interfere with surround module bindings
export VISUAL='nvim'

# Additions to PATH

# Custom
export PATH="$HOME/local/bin:$PATH"
export PATH="$HOME/Downloads/nvim-osx64/bin:$PATH"
# Go
export GOPATH="$HOME/go"
[[ -d $GOPATH ]] && export PATH="$PATH:$GOPATH/bin"
# Krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
# Python
export LIB_PYTHON_PATH="$HOME/Library/Python/3.9"
[[ -d $LIB_PYTHON_PATH ]] && export PATH="$PATH:$LIB_PYTHON_PATH/bin"
# rbenv
export RBENVPATH="$HOME/.rbenv"
[[ -d $RBENVPATH ]] && export PATH="$PATH:$RBENVPATH/bin"
[[ -d $RBENVPATH ]] && export PATH="$PATH:$RBENVPATH/shims"
export RBENV_SHELL=zsh
# Rust
export CARGOPATH="$HOME/.cargo"
[[ -d $CARGOPATH ]] && export PATH="$PATH:$CARGOPATH/bin"

# Homebrew
# eval "$(/opt/homebrew/bin/brew shellenv)"
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

# https://github.com/brianmario/mysql2/issues/795
export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/opt/openssl@1.1/lib"

# Pipe less to highlight
export LESSOPEN="| /opt/homebrew/bin/highlight %s --out-format xterm256 --quiet --force --style solarized-light "
export LESS=" -R"

# Quiet direnv
export DIRENV_LOG_FORMAT=

# ruby-build
# To link Rubies to Homebrew's OpenSSL 1.1 (which is upgraded) add the following to your ~/.zshrc:
# Note: this may interfere with building old versions of Ruby (e.g <2.4) that use OpenSSL <1.1.
# export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=/opt/homebrew/opt/openssl@1.1"
export LDFLAGS="-L/opt/homebrew/opt/readline/lib"
export CPPFLAGS="-I/opt/homebrew/opt/readline/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/readline/lib/pkgconfig"

# https://gitlab.com/gnachman/iterm2/-/wikis/tmux-Integration-Best-Practices#how-do-i-use-shell-integration
export ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX=YES
