# .zshrc

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

LANG='en_US.UTF-8'
LC_COLLATE='en_US.UTF-8'
LC_CTYPE='en_US.UTF-8'
LC_MESSAGES='en_US.UTF-8'
LC_MONETARY='en_US.UTF-8'
LC_NUMERIC='en_US.UTF-8'
LC_TIME='en_US.UTF-8'
LC_ALL='en_US.UTF-8'

# Exports
export EDITOR='nvim'
export JRUBY_OPTS='--dev'
export KEYTIMEOUT=1 # Reduce delay when hitting ESC
export PATH="$HOME/local/bin:$PATH"
export PATH="$PATH:$HOME/bin"
export VISUAL='nvim'

# Aliases
alias brew-refill='brew update && brew upgrade && brew cleanup && brew doctor'
alias ctags="`brew --prefix`/bin/ctags" # Use ctags from homebrew
alias gw="./gradlew"

# Pipe less to highlight
export LESSOPEN="| $(which highlight) %s --out-format xterm256 --quiet --force --style molokai"
export LESS=" -R"
alias less='less -m -g -i -J --underline-special'
alias more='less'

# Replace cat with highlight
alias cat="highlight $1 --out-format xterm256 --quiet --force --style molokai"

# vi-mode bindings
bindkey -v

# History search
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward

# Bind UP and DOWN arrow keys (compatibility fallback
# for Ubuntu 12.04, Fedora 21, and MacOSX 10.9 users)
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Movements
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey '^w' backward-kill-word

# Show insert/normal mode indicator for vim-mode
function zle-keymap-select zle-line-init zle-line-finish {
  # iTerm2 escape codes: https://www.iterm2.com/documentation-escape-codes.html
  case $KEYMAP in
    vicmd)      print -n -- "\033]Pgb0fa00\033\\";;  # normal mode
    viins|main) print -n -- "\033]Pgffffff\033\\";;  # insert mode
  esac
  zle reset-prompt
  zle -R
}
zle -N zle-line-init
zle -N zle-line-finish
zle -N zle-keymap-select

# Disable C-s
stty -ixon

# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"
unsetopt AUTO_NAME_DIRS # https://github.com/rvm/rvm/issues/3091

# AWS CLI completion
AWS_COMPLETER="/usr/local/bin/aws_zsh_completer"
[[ -s $AWS_COMPLETER ]] && source $AWS_COMPLETER

# Base16 Shell
# BASE16_SHELL="$HOME/.config/base16-shell/base16-monokai.dark.sh"
# [[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# iTerm2 shell integration
# ITERM_SHELL="$HOME/.iterm2_shell_integration.zsh"
# [[ -s $ITERM_SHELL ]] && source $ITERM_SHELL

# NVM
export NVM_DIR="/Users/odillem2/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"

# SDKMAN!
setopt clobber
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
setopt noclobber

# direnv
if hash direnv 2>/dev/null; then
  eval "$(direnv hook `basename $SHELL`)"
fi

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[[ -x $(command -v rg) ]] && export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*" --glob "!*.class"'

# k8s
source <(kubectl completion `basename $SHELL`)

# Completions
MODILLE_COMPLETIONS="$HOME/git/github.com/modille/completions/`basename $SHELL`"
[[ -d $MODILLE_COMPLETIONS ]] && fpath=($MODILLE_COMPLETIONS $fpath)

# Private configs
PRIVATE_RC="$HOME/.zshrc-private"
[[ -s $PRIVATE_RC ]] && source $PRIVATE_RC
