# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Note: Try to avoid Nerd Font symbols so that I can copy/paste my prompt when messaging others

# Let iTerm2 take care of this
add_newline = false

# palette = "catppuccin_macchiato"

# Replace the '❯' symbol in the prompt with '$'
[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

# Use a format that makes more sense when copying/pasting terminal output to someone else
[directory]
format = '# in [$path]($style)[$read_only]($read_only_style) '
truncate_to_repo = false
truncation_length = 12
fish_style_pwd_dir_length = 1

[git_branch]
symbol = ''

# I stash things all the time, so don't bother with a stash indicator
[git_status]
stashed = ''

[nodejs]
symbol = 'Node '

[ruby]
symbol = 'Ruby '

# Explicitly disable all other modules
[aws]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[cmd_duration]
disabled = true

[conda]
disabled = true

[container]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[direnv]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[fill]
disabled = true

[fossil_branch]
disabled = true

[fossil_metrics]
disabled = true

[gcloud]
disabled = true

[git_commit]
disabled = true

[git_metrics]
disabled = true

[git_state]
disabled = true

[gleam]
disabled = true

[golang]
disabled = true

[gradle]
disabled = true

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[hg_branch]
disabled = true

[hostname]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[meson]
disabled = true

[mise]
disabled = true

[nats]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[opa]
disabled = true

[os]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pijul_channel]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[rlang]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shell]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[status]
disabled = true

[sudo]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[typst]
disabled = true

[username]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true

# [palettes.catppuccin_frappe]
# rosewater = "#f2d5cf"
# flamingo = "#eebebe"
# pink = "#f4b8e4"
# mauve = "#ca9ee6"
# red = "#e78284"
# maroon = "#ea999c"
# peach = "#ef9f76"
# yellow = "#e5c890"
# green = "#a6d189"
# teal = "#81c8be"
# sky = "#99d1db"
# sapphire = "#85c1dc"
# blue = "#8caaee"
# lavender = "#babbf1"
# text = "#c6d0f5"
# subtext1 = "#b5bfe2"
# subtext0 = "#a5adce"
# overlay2 = "#949cbb"
# overlay1 = "#838ba7"
# overlay0 = "#737994"
# surface2 = "#626880"
# surface1 = "#51576d"
# surface0 = "#414559"
# base = "#303446"
# mantle = "#292c3c"
# crust = "#232634"

# [palettes.catppuccin_latte]
# rosewater = "#dc8a78"
# flamingo = "#dd7878"
# pink = "#ea76cb"
# mauve = "#8839ef"
# red = "#d20f39"
# maroon = "#e64553"
# peach = "#fe640b"
# yellow = "#df8e1d"
# green = "#40a02b"
# teal = "#179299"
# sky = "#04a5e5"
# sapphire = "#209fb5"
# blue = "#1e66f5"
# lavender = "#7287fd"
# text = "#4c4f69"
# subtext1 = "#5c5f77"
# subtext0 = "#6c6f85"
# overlay2 = "#7c7f93"
# overlay1 = "#8c8fa1"
# overlay0 = "#9ca0b0"
# surface2 = "#acb0be"
# surface1 = "#bcc0cc"
# surface0 = "#ccd0da"
# base = "#eff1f5"
# mantle = "#e6e9ef"
# crust = "#dce0e8"

# [palettes.catppuccin_macchiato]
# rosewater = "#f4dbd6"
# flamingo = "#f0c6c6"
# pink = "#f5bde6"
# mauve = "#c6a0f6"
# red = "#ed8796"
# maroon = "#ee99a0"
# peach = "#f5a97f"
# yellow = "#eed49f"
# green = "#a6da95"
# teal = "#8bd5ca"
# sky = "#91d7e3"
# sapphire = "#7dc4e4"
# blue = "#8aadf4"
# lavender = "#b7bdf8"
# text = "#cad3f5"
# subtext1 = "#b8c0e0"
# subtext0 = "#a5adcb"
# overlay2 = "#939ab7"
# overlay1 = "#8087a2"
# overlay0 = "#6e738d"
# surface2 = "#5b6078"
# surface1 = "#494d64"
# surface0 = "#363a4f"
# base = "#24273a"
# mantle = "#1e2030"
# crust = "#181926"

# [palettes.catppuccin_mocha]
# rosewater = "#f5e0dc"
# flamingo = "#f2cdcd"
# pink = "#f5c2e7"
# mauve = "#cba6f7"
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"
